### ISSUE TITLE
get error in testing pyrouge!

### ISSUE THREAD

**Issue by 85405115** [bheinzerling/pyrouge#14]
I run these commands, successfully:
```
git clone https://github.com/bheinzerling/pyrouge
cd pyrouge
python setup.py install
pyrouge_set_rouge_path.py /home/mahsa/ROUGE-1.5.5/
```
But when I write this command, I receive an error:

`python -m pyrouge.test`

Here is this error:
```
2017-12-14 01:53:07,990 [MainThread  ] [INFO ]  Written ROUGE configuration to /tmp/tmpy6pce_k0/rouge_conf.xml
.2017-12-14 01:53:08,505 [MainThread  ] [INFO ]  Processing files in data/SL2003_models_plain_text.
2017-12-14 01:53:08,506 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-10.html.
2017-12-14 01:53:08,506 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-04.html.
2017-12-14 01:53:08,506 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-11.html.
2017-12-14 01:53:08,506 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-25.html.
2017-12-14 01:53:08,507 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-14.html.
2017-12-14 01:53:08,507 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-13.html.
2017-12-14 01:53:08,507 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-01.html.
2017-12-14 01:53:08,507 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-02.html.
2017-12-14 01:53:08,508 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-05.html.
2017-12-14 01:53:08,508 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-23.html.
2017-12-14 01:53:08,508 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-09.html.
2017-12-14 01:53:08,508 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-24.html.
2017-12-14 01:53:08,509 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-15.html.
2017-12-14 01:53:08,509 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-19.html.
2017-12-14 01:53:08,519 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-03.html.
2017-12-14 01:53:08,519 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-12.html.
2017-12-14 01:53:08,520 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-22.html.
2017-12-14 01:53:08,521 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-17.html.
2017-12-14 01:53:08,521 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-08.html.
2017-12-14 01:53:08,522 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-21.html.
2017-12-14 01:53:08,522 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-20.html.
2017-12-14 01:53:08,523 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-18.html.
2017-12-14 01:53:08,523 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-16.html.
2017-12-14 01:53:08,524 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-07.html.
2017-12-14 01:53:08,524 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-06.html.
2017-12-14 01:53:08,525 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpai9wsudt.
.2017-12-14 01:53:08,569 [MainThread  ] [INFO ]  Written ROUGE configuration to /tmp/tmpvsc7_s_k/rouge_conf.xml
2017-12-14 01:53:08,569 [MainThread  ] [INFO ]  Running ROUGE with command /home/mahsa/ROUGE-1.5.5/ROUGE-1.5.5.pl -e /home/mahsa/ROUGE-1.5.5/data -c 95 -2 -1 -U -r 1000 -n 4 -w 1.2 -a -m /tmp/tmpvsc7_s_k/rouge_conf.xml
Cannot open exception db file for reading: /home/mahsa/ROUGE-1.5.5/data/WordNet-2.0.exc.db
E2017-12-14 01:53:09,874 [MainThread  ] [INFO ]  Processing files in data/SL2003_models_rouge_format.
2017-12-14 01:53:09,874 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-10.html.
/home/mahsa/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 4 of the file /home/mahsa/anaconda3/bin/pyrouge_convert_rouge_format_to_plain_text. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
2017-12-14 01:53:09,879 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-04.html.
2017-12-14 01:53:09,881 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-11.html.
2017-12-14 01:53:09,883 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-25.html.
2017-12-14 01:53:09,885 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-14.html.
2017-12-14 01:53:09,887 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-13.html.
2017-12-14 01:53:09,889 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-01.html.
2017-12-14 01:53:09,890 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-02.html.
2017-12-14 01:53:09,892 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-05.html.
2017-12-14 01:53:09,893 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-23.html.
2017-12-14 01:53:09,895 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-09.html.
2017-12-14 01:53:09,896 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-24.html.
2017-12-14 01:53:09,897 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-15.html.
2017-12-14 01:53:09,898 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-19.html.
2017-12-14 01:53:09,899 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-03.html.
2017-12-14 01:53:09,901 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-12.html.
2017-12-14 01:53:09,902 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-22.html.
2017-12-14 01:53:09,903 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-17.html.
2017-12-14 01:53:09,904 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-08.html.
2017-12-14 01:53:09,906 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-21.html.
2017-12-14 01:53:09,907 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-20.html.
2017-12-14 01:53:09,909 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-18.html.
2017-12-14 01:53:09,910 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-16.html.
2017-12-14 01:53:09,912 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-07.html.
2017-12-14 01:53:09,913 [MainThread  ] [INFO ]  Processing SL.P.10.R.A.SL062003-06.html.
2017-12-14 01:53:09,914 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpab6id8d1.
.2017-12-14 01:53:10,475 [MainThread  ] [INFO ]  Writing summaries.
2017-12-14 01:53:10,477 [MainThread  ] [INFO ]  Processing summaries. Saving system files to /tmp/tmph0s8_f0z/system and model files to /tmp/tmph0s8_f0z/model.
2017-12-14 01:53:10,477 [MainThread  ] [INFO ]  Processing files in data/systems_plain.
2017-12-14 01:53:10,477 [MainThread  ] [INFO ]  Processing D30002.M.100.T.A.
2017-12-14 01:53:10,478 [MainThread  ] [INFO ]  Processing D30003.M.100.T.A.
2017-12-14 01:53:10,478 [MainThread  ] [INFO ]  Processing D30001.M.100.T.A.
2017-12-14 01:53:10,479 [MainThread  ] [INFO ]  Processing D30005.M.100.T.A.
2017-12-14 01:53:10,479 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmph0s8_f0z/system.
2017-12-14 01:53:10,479 [MainThread  ] [INFO ]  Processing files in data/models_plain.
2017-12-14 01:53:10,479 [MainThread  ] [INFO ]  Processing D30005.M.100.T.C.
2017-12-14 01:53:10,480 [MainThread  ] [INFO ]  Processing D30002.M.100.T.E.
2017-12-14 01:53:10,480 [MainThread  ] [INFO ]  Processing D30001.M.100.T.C.
2017-12-14 01:53:10,481 [MainThread  ] [INFO ]  Processing D30001.M.100.T.B.
2017-12-14 01:53:10,481 [MainThread  ] [INFO ]  Processing D30003.M.100.T.F.
2017-12-14 01:53:10,482 [MainThread  ] [INFO ]  Processing D30003.M.100.T.C.
2017-12-14 01:53:10,482 [MainThread  ] [INFO ]  Processing D30001.M.100.T.D.
2017-12-14 01:53:10,483 [MainThread  ] [INFO ]  Processing D30005.M.100.T.G.
2017-12-14 01:53:10,483 [MainThread  ] [INFO ]  Processing D30002.M.100.T.C.
2017-12-14 01:53:10,483 [MainThread  ] [INFO ]  Processing D30002.M.100.T.B.
2017-12-14 01:53:10,484 [MainThread  ] [INFO ]  Processing D30005.M.100.T.B.
2017-12-14 01:53:10,484 [MainThread  ] [INFO ]  Processing D30003.M.100.T.B.
2017-12-14 01:53:10,484 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmph0s8_f0z/model.
2017-12-14 01:53:10,486 [MainThread  ] [INFO ]  Written ROUGE configuration to /tmp/tmp6a8qeb0b/rouge_conf.xml
2017-12-14 01:53:10,486 [MainThread  ] [INFO ]  Running ROUGE with command /home/mahsa/ROUGE-1.5.5/ROUGE-1.5.5.pl -e /home/mahsa/ROUGE-1.5.5/data -c 90 -2 -1 -U -r 1000 -n 2 -w 1.2 -a -m data/config_test2.xml -m /tmp/tmp6a8qeb0b/rouge_conf.xml
Cannot open exception db file for reading: /home/mahsa/ROUGE-1.5.5/data/WordNet-2.0.exc.db
Traceback (most recent call last):
  File "/home/mahsa/anaconda3/bin/pyrouge_evaluate_plain_text_files", line 4, in <module>
    __import__('pkg_resources').run_script('pyrouge==0.1.3', 'pyrouge_evaluate_plain_text_files')
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/EGG-INFO/scripts/pyrouge_evaluate_plain_text_files", line 25, in <module>
    main()
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/EGG-INFO/scripts/pyrouge_evaluate_plain_text_files", line 21, in main
    output = rouge.convert_and_evaluate(args.system_id, args.split_sents)
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 364, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 339, in evaluate
    rouge_output = check_output(command).decode("UTF-8")
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/mahsa/ROUGE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/mahsa/ROUGE-1.5.5/data', '-c', '90', '-2', '-1', '-U', '-r', '1000', '-n', '2', '-w', '1.2', '-a', '-m', 'data/config_test2.xml', '-m', '/tmp/tmp6a8qeb0b/rouge_conf.xml']' returned non-zero exit status 255.
E.2017-12-14 01:53:11,148 [MainThread  ] [INFO ]  Writing summaries.
2017-12-14 01:53:11,151 [MainThread  ] [INFO ]  Processing summaries. Saving system files to /tmp/tmpub0odyyt/system and model files to /tmp/tmpub0odyyt/model.
2017-12-14 01:53:11,151 [MainThread  ] [INFO ]  Processing files in data/systems_plain.
2017-12-14 01:53:11,151 [MainThread  ] [INFO ]  Processing D30002.M.100.T.A.
2017-12-14 01:53:11,152 [MainThread  ] [INFO ]  Processing D30003.M.100.T.A.
2017-12-14 01:53:11,152 [MainThread  ] [INFO ]  Processing D30001.M.100.T.A.
2017-12-14 01:53:11,153 [MainThread  ] [INFO ]  Processing D30005.M.100.T.A.
2017-12-14 01:53:11,154 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpub0odyyt/system.
2017-12-14 01:53:11,154 [MainThread  ] [INFO ]  Processing files in data/models_plain.
2017-12-14 01:53:11,154 [MainThread  ] [INFO ]  Processing D30005.M.100.T.C.
2017-12-14 01:53:11,155 [MainThread  ] [INFO ]  Processing D30002.M.100.T.E.
2017-12-14 01:53:11,155 [MainThread  ] [INFO ]  Processing D30001.M.100.T.C.
2017-12-14 01:53:11,156 [MainThread  ] [INFO ]  Processing D30001.M.100.T.B.
2017-12-14 01:53:11,156 [MainThread  ] [INFO ]  Processing D30003.M.100.T.F.
2017-12-14 01:53:11,157 [MainThread  ] [INFO ]  Processing D30003.M.100.T.C.
2017-12-14 01:53:11,157 [MainThread  ] [INFO ]  Processing D30001.M.100.T.D.
2017-12-14 01:53:11,158 [MainThread  ] [INFO ]  Processing D30005.M.100.T.G.
2017-12-14 01:53:11,158 [MainThread  ] [INFO ]  Processing D30002.M.100.T.C.
2017-12-14 01:53:11,159 [MainThread  ] [INFO ]  Processing D30002.M.100.T.B.
2017-12-14 01:53:11,159 [MainThread  ] [INFO ]  Processing D30005.M.100.T.B.
2017-12-14 01:53:11,160 [MainThread  ] [INFO ]  Processing D30003.M.100.T.B.
2017-12-14 01:53:11,160 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpub0odyyt/model.
2017-12-14 01:53:11,162 [MainThread  ] [INFO ]  Written ROUGE configuration to /tmp/tmprdoxel4d/rouge_conf.xml
2017-12-14 01:53:11,162 [MainThread  ] [INFO ]  Running ROUGE with command /home/mahsa/ROUGE-1.5.5/ROUGE-1.5.5.pl -e /home/mahsa/ROUGE-1.5.5/data -c 95 -2 -1 -U -r 1000 -n 4 -w 1.2 -a -m /tmp/tmprdoxel4d/rouge_conf.xml
Cannot open exception db file for reading: /home/mahsa/ROUGE-1.5.5/data/WordNet-2.0.exc.db
Traceback (most recent call last):
  File "/home/mahsa/anaconda3/bin/pyrouge_evaluate_plain_text_files", line 4, in <module>
    __import__('pkg_resources').run_script('pyrouge==0.1.3', 'pyrouge_evaluate_plain_text_files')
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/EGG-INFO/scripts/pyrouge_evaluate_plain_text_files", line 25, in <module>
    main()
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/EGG-INFO/scripts/pyrouge_evaluate_plain_text_files", line 21, in main
    output = rouge.convert_and_evaluate(args.system_id, args.split_sents)
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 364, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/home/mahsa/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 339, in evaluate
    rouge_output = check_output(command).decode("UTF-8")
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/mahsa/ROUGE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/mahsa/ROUGE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmprdoxel4d/rouge_conf.xml']' returned non-zero exit status 255.
E./tmp/tmpeswzphxi/config_test.xml data/config_test.xml
...
======================================================================
ERROR: test_evaluation (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mahsa/pyrouge/pyrouge/tests/Rouge155_test.py", line 156, in test_evaluation
    pyrouge_output = rouge.evaluate(system_id=11).strip()
  File "/home/mahsa/pyrouge/pyrouge/Rouge155.py", line 339, in evaluate
    rouge_output = check_output(command).decode("UTF-8")
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/mahsa/ROUGE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/mahsa/ROUGE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmpvsc7_s_k/rouge_conf.xml']' returned non-zero exit status 255.

======================================================================
ERROR: test_options (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mahsa/pyrouge/pyrouge/tests/Rouge155_test.py", line 218, in test_options
    pyrouge_output = check_output_clean(pyrouge_command)
  File "/home/mahsa/pyrouge/pyrouge/tests/Rouge155_test.py", line 17, in <lambda>
    check_output_clean = lambda c: check_output(c).decode("UTF-8").strip()
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyrouge_evaluate_plain_text_files', '-m', 'data/models_plain', '-s', 'data/systems_plain', '-sfp', 'D(\\d+).M.100.T.A', '-mfp', 'D#ID#.M.100.T.[A-Z]', '-id', '1', '-rargs', '"-e /home/mahsa/ROUGE-1.5.5/data -c 90 -2 -1 -U -r 1000 -n 2 -w 1.2 -a -m data/config_test2.xml"']' returned non-zero exit status 1.

======================================================================
ERROR: test_rouge_for_plain_text (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mahsa/pyrouge/pyrouge/tests/Rouge155_test.py", line 173, in test_rouge_for_plain_text
    pyrouge_output = check_output_clean(pyrouge_command.split())
  File "/home/mahsa/pyrouge/pyrouge/tests/Rouge155_test.py", line 17, in <lambda>
    check_output_clean = lambda c: check_output(c).decode("UTF-8").strip()
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/mahsa/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyrouge_evaluate_plain_text_files', '-m', 'data/models_plain', '-s', 'data/systems_plain', '-sfp', 'D(\\d+).M.100.T.A', '-mfp', 'D#ID#.M.100.T.[A-Z]', '-id', '1']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 11 tests in 3.937s

FAILED (errors=3)


```

Please help me. I dont know what to do?

**Comment by 85405115** [comment]
Hi,
My problem has been solved.
First I like to tell some basic explanations that may be helpful to the others that are new to summarization and ROUGE-1.5.5 and pyrouge...

pyrouge is a python interface to contact with ROUGE-1.5.5 package that is written in Perl.

So you should first download ROUGE-1.5.5 package.

After that, you should download the latest version of the pyrouge package by this command:
`git clone https://github.com/bheinzerling/pyrouge`

Now the pyrouge package has been downloaded and you should go to this directory:
`cd pyrouge`

Install the setup.py file in pyrouge folder by this command:
`python setup.py install`

pyrouge needs to know where is the path to ROUGE-1.5.5 in your computer by running this command:
`pyrouge_set_rouge_path.py /path_to_ROUGE-1.5.5/`
for example in my Ubuntu this is:
`pyrouge_set_rouge_path.py /home/mahsa/ROUGE-1.5.5/`

Now you should test the correctness of the installation by this command:
`python -m pyrouge.test`

But when I run this command I get an error and finally:
```
Ran 11 tests in 3.937s

FAILED (errors=3)
```

I paid attention to the error and i see this in my error:
` Cannot open exception db file for reading: /home/mahsa/ROUGE-1.5.5/data/WordNet-2.0.exc.db`

It means that WordNet-2.0.exc.db file can't be read.

To solve this problem I saw this [link](https://github.com/masters-info-nantes/ter-resume-auto/blob/master/README.md) and it solved my problem.


```
cd data/WordNet-2.0-Exceptions/
rm WordNet-2.0.exc.db # only if exist
./buildExeptionDB.pl . exc WordNet-2.0.exc.db

cd ../
rm WordNet-2.0.exc.db # only if exist
ln -s WordNet-2.0-Exceptions/WordNet-2.0.exc.db WordNet-2.0.exc.db
```

It removes that file and reconstruct a new one. After that i run again `python -m pyrouge.test` and i get:
```
Ran 11 tests in 8.391s

OK
```

Thanks from [bheinzerling](https://github.com/bheinzerling) and [Masters Informatique 2014-2016](https://github.com/masters-info-nantes).
