### ISSUE TITLE
Getting 3 errors out of 11 while testing pyrouge

### ISSUE THREAD

**Issue by OlhaOlha** [bheinzerling/pyrouge#29]
Hi everyone!
While testing if everything is installed correctly, running:
python -m pyrouge.test
I've got  3 errors out if 11.

As I understood the error occurs when execution perl script ROUGE-1.5.5.pl

OSError: [Errno 8] Exec format error: '/home/olha/Desktop/GNLP/Project/fast_abs_rl/ROUGE-1.5.5/ROUGE-1.5.5.pl'
E./tmp/tmpf95nxjbp/config_test.xml data/config_test.xml
...
======================================================================
ERROR: test_evaluation (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/olhasempienv/lib/python3.6/site-packages/pyrouge/tests/Rouge155_test.py", line 156, in test_evaluation
    pyrouge_output = rouge.evaluate(system_id=11).strip()
  File "/olhasempienv/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 342, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/olha/Desktop/GNLP/Project/fast_abs_rl/ROUGE-1.5.5/ROUGE-1.5.5.pl'

======================================================================
ERROR: test_options (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/olhasempienv/lib/python3.6/site-packages/pyrouge/tests/Rouge155_test.py", line 218, in test_options
    pyrouge_output = check_output_clean(pyrouge_command)
  File "/olhasempienv/lib/python3.6/site-packages/pyrouge/tests/Rouge155_test.py", line 17, in <lambda>
    check_output_clean = lambda c: check_output(c).decode("UTF-8").strip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyrouge_evaluate_plain_text_files', '-m', 'data/models_plain', '-s', 'data/systems_plain', '-sfp', 'D(\\d+).M.100.T.A', '-mfp', 'D#ID#.M.100.T.[A-Z]', '-id', '1', '-rargs', '"-e /home/olhamuliava/Desktop/GNLP/Project/fast_abs_rl/ROUGE-1.5.5/data -c 90 -2 -1 -U -r 1000 -n 2 -w 1.2 -a -m data/config_test2.xml"']' returned non-zero exit status 1.

======================================================================
ERROR: test_rouge_for_plain_text (pyrouge.tests.Rouge155_test.PyrougeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/olhasempienv/lib/python3.6/site-packages/pyrouge/tests/Rouge155_test.py", line 173, in test_rouge_for_plain_text
    pyrouge_output = check_output_clean(pyrouge_command.split())
  File "/olhasempienv/lib/python3.6/site-packages/pyrouge/tests/Rouge155_test.py", line 17, in <lambda>
    check_output_clean = lambda c: check_output(c).decode("UTF-8").strip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyrouge_evaluate_plain_text_files', '-m', 'data/models_plain', '-s', 'data/systems_plain', '-sfp', 'D(\\d+).M.100.T.A', '-mfp', 'D#ID#.M.100.T.[A-Z]', '-id', '1']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 11 tests in 0.396s

FAILED (errors=3)

Any ideas?

Any help would be appreciated!

**Comment by astariul** [comment]
@OlhaOlha  How did you fix this ?

**Comment by acrosson** [comment]
@OlhaOlha how did you resolve this?

**Comment by acrosson** [comment]
Nvm. in my case, I forgot a step in the installation of Rouge. Follow this guide, and make sure you do step 6
https://poojithansl7.wordpress.com/2018/08/04/setting-up-rouge/

If there's already a `WordNet-2.0.exc.db` file you'll have to delete it and recreate the symbolic link.
