### ISSUE TITLE
returned non-zero exit status 255.

### ISSUE THREAD

**Issue by kevinborg** [bheinzerling/pyrouge#30]
I am getting this error. Help me please.

![image](https://user-images.githubusercontent.com/16855972/58249254-a16a3200-7d5e-11e9-9518-ccbbef02db17.png)

**Comment by xiongma** [comment]
me too @bheinzerling  Can you help me?

**Comment by xiongma** [comment]
this is running time log
`2019-05-24 14:12:11,257 [MainThread  ] [INFO ]  Set ROUGE home directory to /usr/local/RELEASE-1.5.5.
2019-05-24 14:12:11,257 [MainThread  ] [INFO ]  Writing summaries.
2019-05-24 14:12:11,258 [MainThread  ] [INFO ]  Processing summaries. Saving system files to /tmp/tmp0tdk7ziz/system and model files to /tmp/tmp0tdk7ziz/model.
2019-05-24 14:12:11,258 [MainThread  ] [INFO ]  Processing files in rouge_test/reference.
2019-05-24 14:12:11,258 [MainThread  ] [INFO ]  Processing summary.001.txt.
2019-05-24 14:12:11,258 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmp0tdk7ziz/system.
2019-05-24 14:12:11,258 [MainThread  ] [INFO ]  Processing files in rouge_test/model.
2019-05-24 14:12:11,259 [MainThread  ] [INFO ]  Processing summary.A.001.txt.
2019-05-24 14:12:11,259 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmp0tdk7ziz/model.
2019-05-24 14:12:11,259 [MainThread  ] [INFO ]  Written ROUGE configuration to /tmp/tmpuina_tiw/rouge_conf.xml
2019-05-24 14:12:11,259 [MainThread  ] [INFO ]  Running ROUGE with command /usr/local/RELEASE-1.5.5/ROUGE-1.5.5.pl -e /usr/local/RELEASE-1.5.5/data -c 95 -2 -1 -U -r 1000 -n 4 -w 1.2 -a -m /tmp/tmpuina_tiw/rouge_conf.xml
Illegal division by zero at /usr/local/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450.
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    output = r.convert_and_evaluate()
  File "/opt/modules/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 367, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/opt/modules/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 342, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/opt/modules/anaconda3/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/modules/anaconda3/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/usr/local/RELEASE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmpuina_tiw/rouge_conf.xml']' returned non-zero exit status 255.
`

**Comment by chenjun0210** [comment]
是不是我们跑的是中文的？我也遇到了这个错误

**Comment by ghost** [comment]
I have the same problem, anyone could solve it? Win10, python 3.7

**Comment by xdolnak** [comment]
I followed this tutorial https://poojithansl7.wordpress.com/2018/08/04/setting-up-rouge/ and fixed that error by alterning
`ln -s WordNet-2.0-Exceptions/WordNet-2.0.exc.db WordNet-2.0.exc.db`
to
`ln -sf WordNet-2.0-Exceptions/WordNet-2.0.exc.db WordNet-2.0.exc.db`

**Comment by RakshaAg** [comment]
Please help.
Same problem with windows 10 python 3.6

**Comment by RafaelWO** [comment]
This error also occurs if there are some unwanted characters in either the system or model summaries.
In my case it was the token `<unk>` which caused this error. I simply replaced it by `UNK`.

**Comment by wangzonghui1994** [comment]
> 是不是我们跑的是中文的？我也遇到了这个错误

请问您解决了吗，最后

**Comment by YKJamesMoriarty** [comment]
that is because you did not execute a command with administrator privileges
