### ISSUE TITLE
Error with rouge_conf.xml: write_config_static does not find text files

### ISSUE THREAD

**Issue by KarlDavidson** [bheinzerling/pyrouge#34]
I am working through the simple test case, and despite its simplicity I can't seems to fix the error that it gives me. 

```2020-08-12 16:02:52,958 [MainThread  ] [INFO ]  Set ROUGE home directory to /content/gdrive/My Drive/pyrouge-master/tools/ROUGE-1.5.5/.
2020-08-12 16:02:52,959 [MainThread  ] [INFO ]  Writing summaries.
2020-08-12 16:02:52,960 [MainThread  ] [INFO ]  Processing summaries. Saving system files to /tmp/tmpswh42b4o/system and model files to /tmp/tmpswh42b4o/model.
2020-08-12 16:02:52,960 [MainThread  ] [INFO ]  Processing files in /content/gdrive/My Drive/test/system_summaries/.
2020-08-12 16:02:52,960 [MainThread  ] [INFO ]  Processing test.001.txt.
2020-08-12 16:02:52,961 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpswh42b4o/system.
2020-08-12 16:02:52,961 [MainThread  ] [INFO ]  Processing files in /content/gdrive/My Drive/test/model_summaries/.
2020-08-12 16:02:52,962 [MainThread  ] [INFO ]  Processing test.A.001.txt.
2020-08-12 16:02:52,963 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpswh42b4o/model.

Traceback (most recent call last):
  File "/content/gdrive/My Drive/test/rouge.py", line 9, in <module>
    output = r.convert_and_evaluate()
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 361, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 331, in evaluate
    self.write_config(system_id=system_id)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 315, in write_config
    self._config_file, system_id)
  File "/usr/local/lib/python3.6/dist-packages/pyrouge/Rouge155.py", line 277, in write_config_static
    system_filename_pattern.pattern, system_dir))
Exception: Did not find any files matching the pattern text.(\d+).txt in the system summaries directory /tmp/tmpswh42b4o/system.
```

This seems to be the case because it is not finding the rouge_conf.xml file to write to/with, since that is the next step of the output that I should see, according to the walkthrough. Is there a simple work around for this that I simply overlooked, or is there some glaring issue here? Any help would be greatly appreciated!

**Comment by bheinzerling** [comment]
Looks like a typo. The pattern should be `test.(\d+).txt` instead of `text...`
